version: '2'
services:
    pmssql-app:
        image: pmssql
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pmssql-postgresql:5432/pmssql
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pmssql-postgresql:
        extends:
            file: postgresql.yml
            service: pmssql-postgresql
