version: '2'
services:
    pmssql-postgresql:
        image: postgres:10.4
        volumes:
            - ~/volumes/postgresql/pmssql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pmssql
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
