version: '3.5'
networks:
    pmssql:
services:
    pmssql-postgresql:
        image: postgres:10.4
        container_name: postgresql
        volumes:
            - ~/volumes/postgresql/pmssql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=pmssql
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
        networks:
            - pmssql
